version: '3.8'

services:
  # Service pour l'application Spring Boot
  app:
    build: .
    image: api:1.0.1
    ports:
      - "8080:8080"  # Map le port 8080 de l'hôte vers le port 8080 du conteneur
    read_only: true
    security_opt:
      - no-new-privileges:true
