name: Check vulnerabilities with Semgrep, then Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name : Checkout code
        uses : actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version : "3.x"

      - name: Install Semgrep
        run: |
          pip install --upgrade pip
          pip install semgrep

      - name: List files tracked by Git
        run: git ls-files

      - name: run semgrep
        run: semgrep --config auto --verbose

  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Vérifier le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Authentification à Azure avec az login
      - name: Log in to Azure
        run: |
          az login --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 4. Authentification à Azure Container Registry (ACR)
      - name: Log in to ACR
        run: |
          az acr login --name acr0vvcg5tq4kwx

      # 5. Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t acr0vvcg5tq4kwx.azurecr.io/api:1.0.0 .

      # 6. Pousser l'image vers ACR
      - name: Push Docker image to ACR
        run: |
          docker push acr0vvcg5tq4kwx.azurecr.io/api:1.0.0
